@defaultUrl = http://localhost:3000/student/

### FindAll
GET {{defaultUrl}}

### Create
POST {{defaultUrl}}
Content-Type: application/json

{
    "student_name": "Og Neto",
    "student_email": "ogsnswestos@email.com",
    "student_passwordHash": "1xss456",
    "course_id": "90b15480-e58e-497b-ba53-827f61847f2a"
}

### FindOne
GET {{defaultUrl}}3436f0c3-1a0d-4a20-8ad8-a4bec42be932

### Update
PATCH {{defaultUrl}}04723ecb-08bb-40d2-905e-684ae2c9e1aa
Content-Type: application/json

{
    "student_name": "Og Neto"
}

### Delete
DELETE {{defaultUrl}}0d0f5e83-587e-402d-a169-9279961f8670

### DeleteAll
DELETE {{defaultUrl}}