@defaultUrl = http://localhost:3000/course/

### FindAll
GET {{defaultUrl}}

### FindOne
GET {{defaultUrl}}90b15480-e58e-497b-ba53-827f61847f2a

### Create
POST {{defaultUrl}}
Content-Type: application/json

{
    "course_name": "Math"
}

### Update
PATCH {{defaultUrl}}4c9550a2-bc1b-42e5-8e52-f220f6e6cc2f
Content-Type: application/json

{
    "course_name": "Math"
}

### Delete
DELETE {{defaultUrl}}49f3970b-276c-4ed0-9708-c82abde6786b